// ─── GL prefix rules ──────────────────────────────────────────────────────────
// Any vendor whose financial_row starts with one of these 2-digit prefixes is
// automatically classified as a preset — regardless of vendor name.
// Priority: GL prefix > pair classification > blank-sentinel fallback.
// Add new prefixes here to extend coverage without touching apply-presets logic.
export const GL_PREFIX_RULES: Record<string, string> = {
  '54': 'Do Not Tag (COGS/Non-S&M)', // Cost of Goods - Delivery (54xxx)
  '55': 'Do Not Tag (COGS/Non-S&M)', // Software Tools / Fee Guides (55xxx)
  '60': 'Do Not Tag (COGS/Non-S&M)', // Employee Costs (60xxx)
};

/**
 * Returns the preset channel for a financial_row based on its GL account prefix,
 * or null if no prefix rule matches.
 *
 * Example: "60200 - Benefits Program|..." → "Do Not Tag (COGS/Non-S&M)"
 */
export function getGlPrefixChannel(financial_row: string): string | null {
  const accountNum = financial_row.match(/^(\d+)/)?.[1] ?? '';
  const prefix2 = accountNum.substring(0, 2);
  return GL_PREFIX_RULES[prefix2] ?? null;
}

// ─── Pair classifications ──────────────────────────────────────────────────────
// Key format: "financial_row|entity_name" (pipe separator)
// Auto-generated from Categories_Marketing.xlsx — do not edit manually
export const PAIR_CLASSIFICATIONS: Record<string, string> = {
  "54051 - EDI Expenses|EDI Health Group": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|Data Media Associates, Inc.": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|DrFirst": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|Change Healthcare (Emdeon)": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "55101 - Software Tools|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "55901 - Fee Guides|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60001 - Wages & Salaries|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60002 - Commissions|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60003 - PTO Wage/Salary Accrual|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60004 - Bonuses|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60125 - US Payroll Taxes|Rippling": "Do Not Tag (COGS/Non-S&M)",
  "60125 - US Payroll Taxes|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|United Health Care": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|Elevate.inc": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|Cigna Healthcare": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|UNUM": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|Restaurant-Misc": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|ImpactSearch Partners, LLC": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Direct Recruiters, Inc.": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Zmich Ventures LLC": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Shift Group Holdings, Inc.": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|ISG Partners": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|TechCXO": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Hire With Near LLC": "Do Not Tag (COGS/Non-S&M)",
  "60402 - Employer 4K Expense|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65001 - Utilities - Internet Access|Kenneth Mark Blount Ramp": "Trade Show",
  "65199 - Services - Other/Misc|Vendor-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65199 - Services - Other/Misc|I'm The Chef Too": "Do Not Tag (COGS/Non-S&M)",
  "65199 - Services - Other/Misc|Beam": "Do Not Tag (COGS/Non-S&M)",
  "65199 - Services - Other/Misc|Kenneth Mark Blount Ramp": "Trade Show",
  "65401 - Tools - Software Licenses|StoryPath LLC": "Other",
  "65401 - Tools - Software Licenses|Ethos transforming education": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Retention.com": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Clay Labs Inc": "Sales Development",
  "65401 - Tools - Software Licenses|Semrush": "SEO / Organic",
  "65401 - Tools - Software Licenses|Salesforce": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|monday.com": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Hubspot": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|LinkedIn": "Paid Social",
  "65401 - Tools - Software Licenses|cleverbridge": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|WiseStamp": "Email",
  "65401 - Tools - Software Licenses|Frase": "SEO / Organic",
  "65401 - Tools - Software Licenses|Canva": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Microsoft Advertising": "Paid Search",
  "65401 - Tools - Software Licenses|Eleventh & Gather": "Trade Show",
  "65401 - Tools - Software Licenses|One Click / DrDDS / Recordlinc": "Sales Development",
  "65401 - Tools - Software Licenses|OpenAI": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|HeyReach": "Paid Social",
  "65401 - Tools - Software Licenses|GetEmails": "Other",
  "65401 - Tools - Software Licenses|SPYFU": "SEO / Organic",
  "65401 - Tools - Software Licenses|Spotify Ad Studio": "Paid Search",
  "65401 - Tools - Software Licenses|Gong.io Inc": "Sales Development",
  "65401 - Tools - Software Licenses|Instantly.Ai": "Email",
  "65401 - Tools - Software Licenses|OpportunityMagic": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Netronix Integration": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Aventri": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Kenneth Mark Blount Ramp": "Trade Show",
  "65401 - Tools - Software Licenses|XAPPEX": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Vendor-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Sean Gove Ramp": "Partner",
  "65401 - Tools - Software Licenses|Photoroom": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|QRTiger": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|ManyChat": "Paid Social",
  "65401 - Tools - Software Licenses|Inbox Navigator": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Bitly": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Microsoft": "Paid Search",
  "65401 - Tools - Software Licenses|Interact": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|ElevenLabs": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Serper": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|QR Code Generator": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Zapier": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Squirrels": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Moz": "SEO / Organic",
  "65401 - Tools - Software Licenses|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Amazon.com - US": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Vendor-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|BestBuy - US": "Trade Show",
  "65501 - Supplies - General Office|Sean Gove Ramp": "Partner",
  "65501 - Supplies - General Office|Trevor Macon": "Trade Show",
  "65501 - Supplies - General Office|Midwest Dental": "Partner",
  "65501 - Supplies - General Office|Target": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Allie Hafliger Ramp": "Trade Show",
  "65501 - Supplies - General Office|Walgreens": "Trade Show",
  "65501 - Supplies - General Office|The UPS Store": "Trade Show",
  "65501 - Supplies - General Office|Apple": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Harry & David": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Staples - US": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Victoria Lane Ramp": "Trade Show",
  "65501 - Supplies - General Office|Halle Eicher Ramp": "Trade Show",
  "65501 - Supplies - General Office|Monica Cody Clark Ramp": "Trade Show",
  "65501 - Supplies - General Office|Kenneth Mark Blount Ramp": "Trade Show",
  "65501 - Supplies - General Office|Shahrzad Nadizadeh Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Sara Ataollahi Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Prime Video": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Dollar General": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Shoppers Drug Mart": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|Fedex": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|USPS": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|MP PACK-N-MAIL": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|Harry & David": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|Kenneth Mark Blount Ramp": "Trade Show",
  "65502 - Supplies - Postage|Sarah Lamb Ramp": "Trade Show",
  "65502 - Supplies - Postage|Carlson Chiles Ramp": "Trade Show",
  "65601 - Travel and Lodging|Hotel-Misc (US)": "Trade Show",
  "65601 - Travel and Lodging|Hilton": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Delta Air Lines": "Trade Show",
  "65601 - Travel and Lodging|Gregory Wu DMD": "Trade Show",
  "65601 - Travel and Lodging|American Express": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Kenneth Mark Blount Ramp": "Trade Show",
  "65601 - Travel and Lodging|The Fractional Match LLC (Cassie Tallon)": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Gary Long Ramp": "Trade Show",
  "65601 - Travel and Lodging|The Ritz-Carlton Aruba": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Allie Hafliger Ramp": "Trade Show",
  "65601 - Travel and Lodging|Sean Gove Ramp": "Trade Show",
  "65601 - Travel and Lodging|Jake Weber Ramp": "Trade Show",
  "65601 - Travel and Lodging|United Airlines": "Trade Show",
  "65601 - Travel and Lodging|Jana Macon Ramp": "Trade Show",
  "65601 - Travel and Lodging|Shahrzad Nadizadeh Ramp": "Trade Show",
  "65601 - Travel and Lodging|American Airlines": "Trade Show",
  "65601 - Travel and Lodging|Southwest Airlines": "Trade Show",
  "65601 - Travel and Lodging|Guestrs Hotel": "Trade Show",
  "65601 - Travel and Lodging|Hanna Brittain Ramp": "Trade Show",
  "65601 - Travel and Lodging|Scott Poitevent Ramp": "Trade Show",
  "65601 - Travel and Lodging|Ashleigh Culpepper Ramp": "Trade Show",
  "65601 - Travel and Lodging|Julia Duncan Ramp": "Trade Show",
  "65601 - Travel and Lodging|Trevor Macon": "Trade Show",
  "65601 - Travel and Lodging|Trade Show Planners Ll": "Trade Show",
  "65601 - Travel and Lodging|Sarah Lamb Ramp": "Trade Show",
  "65601 - Travel and Lodging|Andrew Ward Ramp": "Trade Show",
  "65601 - Travel and Lodging|Suzanne Henderson Ramp": "Trade Show",
  "65601 - Travel and Lodging|Carlson Chiles Ramp": "Trade Show",
  "65601 - Travel and Lodging|Travis Grawey Ramp": "Trade Show",
  "65601 - Travel and Lodging|Halle Eicher Ramp": "Trade Show",
  "65601 - Travel and Lodging|Shannon Murry Ramp": "Trade Show",
  "65601 - Travel and Lodging|Brandon Savage Ramp": "Trade Show",
  "65601 - Travel and Lodging|Marvin Brown Ramp": "Trade Show",
  "65601 - Travel and Lodging|Trysta Napper Ramp": "Trade Show",
  "65601 - Travel and Lodging|Big Cedar Lodge": "Trade Show",
  "65601 - Travel and Lodging|Diana Dipierro Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Victoria Lane Ramp": "Trade Show",
  "65601 - Travel and Lodging|Megan Smith Ramp": "Trade Show",
  "65601 - Travel and Lodging|Tyler McComas Ramp": "Trade Show",
  "65601 - Travel and Lodging|Restaurant-Misc": "Trade Show",
  "65601 - Travel and Lodging|Eric Dawe Ramp": "Trade Show",
  "65601 - Travel and Lodging|Katie May Ramp": "Trade Show",
  "65601 - Travel and Lodging|Monica Cody Clark Ramp": "Trade Show",
  "65601 - Travel and Lodging|Jonlee Anderson Ramp": "Trade Show",
  "65601 - Travel and Lodging|Bowen Riddle Ramp": "Trade Show",
  "65601 - Travel and Lodging|Robin Bowling Ramp": "Trade Show",
  "65601 - Travel and Lodging|Expo Housing Management L": "Trade Show",
  "65601 - Travel and Lodging|Dmitriy Zinger Ramp": "Trade Show",
  "65601 - Travel and Lodging|Jason Anderson Ramp": "Trade Show",
  "65601 - Travel and Lodging|Jonathan Booher Ramp": "Trade Show",
  "65601 - Travel and Lodging|trpts.me": "Trade Show",
  "65601 - Travel and Lodging|Kennedy kennedy.dalsing@curvedental Ramp": "Trade Show",
  "65601 - Travel and Lodging|Vendor-Misc (US)": "Trade Show",
  "65601 - Travel and Lodging|Summer Shack": "Trade Show",
  "65601 - Travel and Lodging|Chateau Elan": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Brian Syphoe Ramp": "Trade Show",
  "65601 - Travel and Lodging|Rocky Mountain Chocolate Factory": "Trade Show",
  "65601 - Travel and Lodging|CrystalPlus.com": "Trade Show",
  "65601 - Travel and Lodging|Clinton": "Trade Show",
  "65601 - Travel and Lodging|Air Canada": "Trade Show",
  "65601 - Travel and Lodging|Amazon.com - US": "Trade Show",
  "65601 - Travel and Lodging|Aa Kiosk": "Trade Show",
  "65601 - Travel and Lodging|Albertsons Market": "Trade Show",
  "65601 - Travel and Lodging|Aruba Wastewater Susta": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Travel Right": "Trade Show",
  "65601 - Travel and Lodging|Southernlivingst2691": "Trade Show",
  "65601 - Travel and Lodging|Fry's Food Stores": "Trade Show",
  "65601 - Travel and Lodging|Evolve By Hudson": "Trade Show",
  "65601 - Travel and Lodging|ChurroStar": "Trade Show",
  "65601 - Travel and Lodging|3266 Sat Adina'S Market": "Trade Show",
  "65601 - Travel and Lodging|Tripadvisor": "Trade Show",
  "65601 - Travel and Lodging|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Restaurant-Misc": "Trade Show",
  "65602 - Meals & Entertainment|Kenneth Mark Blount Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Hotel-Misc (US)": "Trade Show",
  "65602 - Meals & Entertainment|Sam's Club": "Trade Show",
  "65602 - Meals & Entertainment|Julia Duncan Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Gary Long Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Trevor Macon": "Trade Show",
  "65602 - Meals & Entertainment|Sean Gove Ramp": "Trade Show",
  "65602 - Meals & Entertainment|KAK Project Management": "Other",
  "65602 - Meals & Entertainment|Harry & David": "Trade Show",
  "65602 - Meals & Entertainment|Gregory Wu DMD": "Trade Show",
  "65602 - Meals & Entertainment|Victoria Lane Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Marvin Brown Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Carlson Chiles Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Hanna Brittain Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Vet Together": "Trade Show",
  "65602 - Meals & Entertainment|Society": "Trade Show",
  "65602 - Meals & Entertainment|Payless Foods": "Trade Show",
  "65602 - Meals & Entertainment|Publix": "Trade Show",
  "65602 - Meals & Entertainment|Sarah Lamb Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Vendor-Misc (US)": "Trade Show",
  "65602 - Meals & Entertainment|Fandango": "Trade Show",
  "65602 - Meals & Entertainment|Jonathan Booher Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Jeff Beck Ramp": "Trade Show",
  "65602 - Meals & Entertainment|McCormick Place": "Trade Show",
  "65602 - Meals & Entertainment|Table Covers": "Trade Show",
  "65602 - Meals & Entertainment|Shannon Murry Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Hudson News": "Trade Show",
  "65602 - Meals & Entertainment|Hugman's Oasis": "Trade Show",
  "65602 - Meals & Entertainment|Camryn Banks Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Shahrzad Nadizadeh Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Vail Wine Shop & Tasting Room": "Trade Show",
  "65602 - Meals & Entertainment|Amira Hammond Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Kennedy kennedy.dalsing@curvedental Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Robin Bowling Ramp": "Trade Show",
  "65602 - Meals & Entertainment|LOOK Dine-In Cinemas": "Trade Show",
  "65602 - Meals & Entertainment|Savi Provisions": "Trade Show",
  "65602 - Meals & Entertainment|Boston": "Trade Show",
  "65602 - Meals & Entertainment|wsdot": "Trade Show",
  "65602 - Meals & Entertainment|Brandon Cluff Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Allie Hafliger Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Squeezed": "Trade Show",
  "65602 - Meals & Entertainment|Lance Robinson Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Josh Edenfield Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Trysta Napper Ramp": "Trade Show",
  "65602 - Meals & Entertainment|COLORADO CONVETION CENTER": "Trade Show",
  "65602 - Meals & Entertainment|Jackson Lettich Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Jonlee Anderson Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Halle Eicher Ramp": "Trade Show",
  "65602 - Meals & Entertainment|High Dunes": "Trade Show",
  "65602 - Meals & Entertainment|Instacart": "Trade Show",
  "65602 - Meals & Entertainment|Evolve": "Trade Show",
  "65602 - Meals & Entertainment|Paradies Lagardere - CLT": "Trade Show",
  "65602 - Meals & Entertainment|Piroshky Piroshky": "Trade Show",
  "65602 - Meals & Entertainment|Slate Market": "Trade Show",
  "65602 - Meals & Entertainment|Dmitriy Zinger Ramp": "Trade Show",
  "65602 - Meals & Entertainment|3269 Sat Stars Of San": "Trade Show",
  "65602 - Meals & Entertainment|Julia Smith Ramp": "Trade Show",
  "65602 - Meals & Entertainment|San Antonio Gelato": "Trade Show",
  "65602 - Meals & Entertainment|TouchTunes": "Trade Show",
  "65602 - Meals & Entertainment|The Brick Room": "Trade Show",
  "65602 - Meals & Entertainment|Atlanta Daily Worl": "Trade Show",
  "65602 - Meals & Entertainment|Chateau Elan Winery & Resort": "Trade Show",
  "65602 - Meals & Entertainment|Bam Bam": "Trade Show",
  "65602 - Meals & Entertainment|Asters Patisserie": "Trade Show",
  "65602 - Meals & Entertainment|Your Business Center": "Trade Show",
  "65602 - Meals & Entertainment|Sky Market": "Trade Show",
  "65602 - Meals & Entertainment|Cibo Express": "Trade Show",
  "65602 - Meals & Entertainment|Centralpointemkt": "Trade Show",
  "65602 - Meals & Entertainment|Deseret News": "Trade Show",
  "65602 - Meals & Entertainment|Motown Greatest Hits": "Trade Show",
  "65602 - Meals & Entertainment|Hartsfield-Jackson Atlanta International Airport": "Trade Show",
  "65602 - Meals & Entertainment|City Market Coffee": "Trade Show",
  "65602 - Meals & Entertainment|Chateau Elan": "Trade Show",
  "65602 - Meals & Entertainment|Piedmont Park": "Trade Show",
  "65602 - Meals & Entertainment|Kansas City": "Trade Show",
  "65602 - Meals & Entertainment|Tripadvisor": "Trade Show",
  "65602 - Meals & Entertainment|Bodega Den": "Trade Show",
  "65602 - Meals & Entertainment|11alive": "Trade Show",
  "65602 - Meals & Entertainment|Rhino Market & Deli": "Trade Show",
  "65602 - Meals & Entertainment|Amazon Fresh": "Trade Show",
  "65602 - Meals & Entertainment|Longo's": "Trade Show",
  "65602 - Meals & Entertainment|Evolve By Hudson": "Trade Show",
  "65602 - Meals & Entertainment|District News": "Trade Show",
  "65602 - Meals & Entertainment|Southern Connector": "Trade Show",
  "65602 - Meals & Entertainment|oxxo": "Trade Show",
  "65602 - Meals & Entertainment|Duke City Art & Frame": "Trade Show",
  "65602 - Meals & Entertainment|CIBO Express Gourmet Market": "Trade Show",
  "65602 - Meals & Entertainment|Red Sail Sports": "Trade Show",
  "65602 - Meals & Entertainment|(No vendor — journal/payroll/accrual)": "Trade Show",
  "65603 - Parking & Cabs|Uber": "Trade Show",
  "65603 - Parking & Cabs|Hartsfield-Jackson Atlanta International Airport": "Trade Show",
  "65603 - Parking & Cabs|Gregory Wu DMD": "Trade Show",
  "65603 - Parking & Cabs|Kenneth Mark Blount Ramp": "Trade Show",
  "65603 - Parking & Cabs|Gary Long Ramp": "Trade Show",
  "65603 - Parking & Cabs|Sean Gove Ramp": "Trade Show",
  "65603 - Parking & Cabs|Massachusetts Convention Center Authority": "Trade Show",
  "65603 - Parking & Cabs|SLC Airport Parking": "Trade Show",
  "65603 - Parking & Cabs|Trevor Macon": "Trade Show",
  "65603 - Parking & Cabs|Sarah Lamb Ramp": "Trade Show",
  "65603 - Parking & Cabs|The Fractional Match LLC (Cassie Tallon)": "Trade Show",
  "65603 - Parking & Cabs|Julia Duncan Ramp": "Trade Show",
  "65603 - Parking & Cabs|Carlson Chiles Ramp": "Trade Show",
  "65603 - Parking & Cabs|Shannon Murry Ramp": "Trade Show",
  "65603 - Parking & Cabs|Chantelle Camareno Ramp": "Trade Show",
  "65603 - Parking & Cabs|Shahrzad Nadizadeh Ramp": "Trade Show",
  "65603 - Parking & Cabs|ROYAL TAXI": "Trade Show",
  "65603 - Parking & Cabs|Hanna Brittain Ramp": "Trade Show",
  "65603 - Parking & Cabs|Vendor-Misc (US)": "Trade Show",
  "65603 - Parking & Cabs|Jake Weber Ramp": "Trade Show",
  "65603 - Parking & Cabs|Charleston Co Parking": "Trade Show",
  "65603 - Parking & Cabs|National Car Rental": "Trade Show",
  "65603 - Parking & Cabs|Lance Robinson Ramp": "Trade Show",
  "65603 - Parking & Cabs|Jonlee Anderson Ramp": "Trade Show",
  "65603 - Parking & Cabs|Atlanta Airport": "Trade Show",
  "65603 - Parking & Cabs|Ashleigh Culpepper Ramp": "Trade Show",
  "65603 - Parking & Cabs|Marvin Brown Ramp": "Trade Show",
  "65603 - Parking & Cabs|Jana Macon Ramp": "Trade Show",
  "65603 - Parking & Cabs|Limoisine Driver": "Trade Show",
  "65603 - Parking & Cabs|Amira Hammond Ramp": "Trade Show",
  "65603 - Parking & Cabs|Hotel-Misc (US)": "Trade Show",
  "65603 - Parking & Cabs|Atlanta": "Trade Show",
  "65603 - Parking & Cabs|The Parking Spot": "Trade Show",
  "65603 - Parking & Cabs|Trysta Napper Ramp": "Trade Show",
  "65603 - Parking & Cabs|Peachy Airport Parking": "Trade Show",
  "65603 - Parking & Cabs|Robin Bowling Ramp": "Trade Show",
  "65603 - Parking & Cabs|Maddie Radivonik Ramp": "Trade Show",
  "65603 - Parking & Cabs|Victoria Lane Ramp": "Trade Show",
  "65603 - Parking & Cabs|Camryn Banks Ramp": "Trade Show",
  "65603 - Parking & Cabs|Jackson Lettich Ramp": "Trade Show",
  "65603 - Parking & Cabs|Dan Westmoreland Ramp": "Trade Show",
  "65603 - Parking & Cabs|Taxi": "Trade Show",
  "65603 - Parking & Cabs|Tez Safewayprkgsundiallot": "Trade Show",
  "65603 - Parking & Cabs|Premium Parking": "Trade Show",
  "65603 - Parking & Cabs|Brandon Cluff Ramp": "Trade Show",
  "65603 - Parking & Cabs|Domingo Taxi": "Trade Show",
  "65603 - Parking & Cabs|Clinton National Airport LIT": "Trade Show",
  "65603 - Parking & Cabs|Three D Development": "Trade Show",
  "65603 - Parking & Cabs|CNBC Stores": "Trade Show",
  "65603 - Parking & Cabs|SFMTA": "Trade Show",
  "65603 - Parking & Cabs|Seattle Meter Parking": "Trade Show",
  "65604 - Mileage and Car Rentals|Lyft": "Trade Show",
  "65604 - Mileage and Car Rentals|Gary Long Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Robin Bowling Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|National Car Rental": "Trade Show",
  "65604 - Mileage and Car Rentals|Vendor-Misc (US)": "Trade Show",
  "65604 - Mileage and Car Rentals|Trysta Napper Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Marvin Brown Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Alamo": "Trade Show",
  "65604 - Mileage and Car Rentals|Monica Cody Clark Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|The Fractional Match LLC (Cassie Tallon)": "Trade Show",
  "65604 - Mileage and Car Rentals|Allie Hafliger Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Julia Duncan Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Hertz": "Trade Show",
  "65604 - Mileage and Car Rentals|Hanna Brittain Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|KAK Project Management": "Do Not Tag (COGS/Non-S&M)",
  "65604 - Mileage and Car Rentals|Kristie Dame Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Trevor Macon": "Trade Show",
  "65604 - Mileage and Car Rentals|Victoria Lane Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Jeff Beck Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Kennedy kennedy.dalsing@curvedental Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Ashleigh Culpepper Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Chantelle Camareno Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|LeAnn Scott Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Amira Hammond Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Camryn Banks Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Sean Gove Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Shannon Murry Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Gregory Wu DMD": "Trade Show",
  "65604 - Mileage and Car Rentals|Brandon Cluff Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Julia Smith Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Lance Robinson Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Jackson Lettich Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Jana Macon Ramp": "Trade Show",
  "65604 - Mileage and Car Rentals|Clinton": "Trade Show",
  "65604 - Mileage and Car Rentals|(No vendor — journal/payroll/accrual)": "Trade Show",
  "65605 - Internal Company Events|Fairmont El San Juan Hotel": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Delta Air Lines": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Restaurant-Misc": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Destination Puerto Rico": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Hotel-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Agency 44 LLC": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Lapdog": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Andrew Ward Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Gary Long Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Jake Weber Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|KAESER BLAIR INCORPORATED": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Gift & Souvenirs": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|CrystalPlus.com": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|American Express": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Gift Card Granny": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Instacart": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Immersive Group Gaming Li": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Chateau Elan Winery & Resort": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Space Needle": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Successories": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Amazon.com - US": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|PayPal": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Publix": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|Name Badge Productions": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|FunKids Sports Association": "Do Not Tag (COGS/Non-S&M)",
  "65605 - Internal Company Events|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65901 - Fees - Bank Charges|Chateau Elan Winery & Resort": "Do Not Tag (COGS/Non-S&M)",
  "65901 - Fees - Bank Charges|Gary Long Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65901 - Fees - Bank Charges|25470 Care Credit": "Do Not Tag (COGS/Non-S&M)",
  "69301 - Legal|Freeman Mathis & Gary, LLP": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|KAK Project Management": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Kenneth Mark Blount Ramp": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Bosslady Marketing": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Trevor Macon": "Trade Show",
  "69601 - Consulting Fees Paid|DEBORAH E. BUSH": "SEO / Organic",
  "69601 - Consulting Fees Paid|Gregory Wu DMD": "Trade Show",
  "69601 - Consulting Fees Paid|Hyperscayle LLC": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Edward Cole Henson": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Julia Fuhrman": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Amy Kitti": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Hypha HubSpot Development": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|The Fractional Match LLC (Cassie Tallon)": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|GAVIN MCDONNELL": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Strategic Conferences & Events": "Trade Show",
  "69601 - Consulting Fees Paid|Ben Tanksley": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|RevTech Partners": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Jama Bryan": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Chloe Macon": "Paid Social",
  "69601 - Consulting Fees Paid|Magnifident, Inc.": "Referral",
  "69601 - Consulting Fees Paid|ETHAN MCDONNELL": "Do Not Tag (COGS/Non-S&M)",
  "70001 - Direct Mailing Costs|ULINE": "Partner",
  "70001 - Direct Mailing Costs|Sticker Mule": "Trade Show",
  "70001 - Direct Mailing Costs|USPS": "Partner",
  "70501 - Advertising - Print|Smartpress": "Trade Show",
  "70501 - Advertising - Print|Fugio cent": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Google Ads": "Paid Search",
  "70551 - Advertising - Electronic|Facebook": "Paid Social",
  "70551 - Advertising - Electronic|Ascenditt": "Paid Search",
  "70551 - Advertising - Electronic|Capterra": "Review Sites",
  "70551 - Advertising - Electronic|Vibe": "Paid Search",
  "70551 - Advertising - Electronic|Belmont Publications Inc": "Paid Search",
  "70551 - Advertising - Electronic|Dentistry In General": "Partner",
  "70551 - Advertising - Electronic|Breakaway Practice LLC": "Trade Show",
  "70551 - Advertising - Electronic|BURGOS MEDIA LLC": "Paid Social",
  "70551 - Advertising - Electronic|Salem Media Group": "Paid Search",
  "70551 - Advertising - Electronic|Reddit": "Paid Social",
  "70551 - Advertising - Electronic|CrystalPlus.com": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Crystal Central": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Endeavor Business Media": "SEO / Organic",
  "70551 - Advertising - Electronic|Frase": "SEO / Organic",
  "70551 - Advertising - Electronic|Restaurant-Misc": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|American Express": "Referral",
  "70551 - Advertising - Electronic|Semrush": "SEO / Organic",
  "70551 - Advertising - Electronic|ATW Communications (Ricardo Vega)": "Partner",
  "70551 - Advertising - Electronic|Crown Council": "Partner",
  "70551 - Advertising - Electronic|Taboola": "Paid Search",
  "70551 - Advertising - Electronic|Inbox Navigator": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Parking": "Trade Show",
  "70599 - Advertising - Other|The Fractional Match LLC (Cassie Tallon)": "Partner",
  "70599 - Advertising - Other|Chloe Macon": "Paid Social",
  "70599 - Advertising - Other|Stock Supply LLC": "Trade Show",
  "70599 - Advertising - Other|Software Advice": "Review Sites",
  "70599 - Advertising - Other|American Express": "Referral",
  "70599 - Advertising - Other|Cision US Inc.": "SEO / Organic",
  "70599 - Advertising - Other|Dentaltown.com LLC": "Paid Search",
  "70599 - Advertising - Other|Minuteman Press Suwanee A Division of Diversified Printing Solutions Inc.": "Trade Show",
  "70599 - Advertising - Other|Adam C. Garrett": "Do Not Tag (COGS/Non-S&M)",
  "70599 - Advertising - Other|Crown Council": "Partner",
  "70599 - Advertising - Other|Zar Dental Consulting": "Referral",
  "70599 - Advertising - Other|Dr. Scott Leune": "Trade Show",
  "70599 - Advertising - Other|Google Ads": "Paid Search",
  "70599 - Advertising - Other|Whova": "Do Not Tag (COGS/Non-S&M)",
  "70599 - Advertising - Other|Comfort Dental Group, Inc": "Partner",
  "70599 - Advertising - Other|Midtown Technology Group (Michael DeWitt)": "Partner",
  "70599 - Advertising - Other|Solution Start Corp. (Jimmy Georgiou) Demetrios Andritsogiannis": "Partner",
  "70599 - Advertising - Other|1201AM CREATIVE, LLC": "SEO / Organic",
  "70599 - Advertising - Other|Masserano Real Estate Consulting": "Partner",
  "70599 - Advertising - Other|Inland IT": "Partner",
  "70599 - Advertising - Other|Infinity Data Comm Inc.": "Partner",
  "70599 - Advertising - Other|Lightning IT Services, Inc.": "Partner",
  "70599 - Advertising - Other|AccommoDental Media": "Partner",
  "70599 - Advertising - Other|Delmain Analytics LLC": "Partner",
  "70599 - Advertising - Other|ATW Communications (Ricardo Vega)": "Partner",
  "70599 - Advertising - Other|Xcalibur Design": "Partner",
  "70599 - Advertising - Other|Carla Cohn": "Referral",
  "70599 - Advertising - Other|Florida Dental": "Trade Show",
  "70599 - Advertising - Other|Colleen Huff": "Referral",
  "70599 - Advertising - Other|Spotify Ad Studio": "Paid Social",
  "70599 - Advertising - Other|(No vendor — journal/payroll/accrual)": "Other",
  "70601 - Trade Show - Registrations|Dr. Scott Leune": "Trade Show",
  "70601 - Trade Show - Registrations|Gregory Wu DMD": "Trade Show",
  "70601 - Trade Show - Registrations|Clear Coaching Ltd.": "Trade Show",
  "70601 - Trade Show - Registrations|Crown Council": "Trade Show",
  "70601 - Trade Show - Registrations|Dental Boards Ace": "Trade Show",
  "70601 - Trade Show - Registrations|UMKC Dental Alumni": "Trade Show",
  "70601 - Trade Show - Registrations|Freeman": "Trade Show",
  "70601 - Trade Show - Registrations|AAP": "Trade Show",
  "70601 - Trade Show - Registrations|Shepard Exposition Services Inc": "Trade Show",
  "70601 - Trade Show - Registrations|American Academy of Dental Practice Administration": "Trade Show",
  "70601 - Trade Show - Registrations|Carla Cohn": "Trade Show",
  "70601 - Trade Show - Registrations|Greater Atlanta Dental Foundation": "Trade Show",
  "70601 - Trade Show - Registrations|Oregon Convention Center": "Trade Show",
  "70601 - Trade Show - Registrations|Eventbrite": "Trade Show",
  "70601 - Trade Show - Registrations|Connecticut State Dental Association": "Trade Show",
  "70601 - Trade Show - Registrations|Connecticut Society Of": "Trade Show",
  "70601 - Trade Show - Registrations|EFFECTIVE DENTISTRY": "Trade Show",
  "70601 - Trade Show - Registrations|Dallas County Dental Society": "Trade Show",
  "70601 - Trade Show - Registrations|Atlanta Dental Supply": "Trade Show",
  "70601 - Trade Show - Registrations|COLORADO CONVETION CENTER": "Trade Show",
  "70601 - Trade Show - Registrations|Ontario Dental Association": "Trade Show",
  "70601 - Trade Show - Registrations|Convention Data Services": "Trade Show",
  "70601 - Trade Show - Registrations|Restaurant-Misc": "Trade Show",
  "70601 - Trade Show - Registrations|MidwestDental": "Trade Show",
  "70601 - Trade Show - Registrations|Smile Source": "Trade Show",
  "70601 - Trade Show - Registrations|Gift Card": "Trade Show",
  "70601 - Trade Show - Registrations|Amazon.com - US": "Trade Show",
  "70601 - Trade Show - Registrations|Hotel-Misc (US)": "Trade Show",
  "70601 - Trade Show - Registrations|National Denturist Association": "Trade Show",
  "70601 - Trade Show - Registrations|Fedex": "Trade Show",
  "70601 - Trade Show - Registrations|Sam's Club": "Trade Show",
  "70601 - Trade Show - Registrations|Robin Bowling Ramp": "Trade Show",
  "70601 - Trade Show - Registrations|Lidl": "Trade Show",
  "70601 - Trade Show - Registrations|(No vendor — journal/payroll/accrual)": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|KAESER BLAIR INCORPORATED": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Exhibits South": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Halo Branded Solutions": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Freeman": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Expoprep": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Dr. Scott Leune": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Smile Source": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Metro Denver Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Hinman Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Aramark Services, Inc": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Washington State Denta": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Trade Show Planners Ll": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Seattle Convention Center": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Sodexo Live!": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|JW Marriott Camelback Inn": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|McCormick Place": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Jack Nadel International": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Ags Expo": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Restaurant-Misc": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|GES": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Cision US Inc.": "SEO / Organic",
  "70602 - Trade Show - Materials and Rentals|PSAV": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Fern Expo": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Gregory Wu DMD": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Florida Dental": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Virtual Dontics": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Allie Hafliger Ramp": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Tory Burch": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|1201AM CREATIVE, LLC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|The Fractional Match LLC (Cassie Tallon)": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Aadom": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|EDI Health Group": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Dental Medical Billing": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Prg": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Don Ross Nabb Production Companies": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Massachusetts Convention Center Authority": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Amazon.com - US": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Maritz Global Events": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|ASN, INC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Ccld": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Demers Exposition Services": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|MARITZ": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Advanced Tradeshow Technology": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Opportunityretreiv": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Chicago Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Colleen Huff": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|projection.com": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Spectrum Audio Visual": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Eleventh & Gather": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|OPTEL TECHNOLOGY LLC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Custom Registration": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Dental Boards Ace": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Table Covers": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|A-1 Rentals": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Mid-Continent Dental Congress": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Greater St. Louis Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Jp Display": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Production company": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|TRENDY REP GROUP INC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|ARPA-E": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|TRADESHOW MULTIMEDIA INC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Sticker Mule": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|OfficeSignCompany": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Sean Gove Ramp": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Displays2go": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Hollister": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Edlen Electrical Exhibition Services": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Jonlee Anderson Ramp": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Wscc Pfd": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Joy Displays": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|AAP": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|B&H Photo": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|PlatePass": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Connecticut State Dental Association": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Spotify Ad Studio": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|(No vendor — journal/payroll/accrual)": "Trade Show",
  "70801 - Promo Events|Amazon.com - US": "Other",
  "70801 - Promo Events|Smiles For Recovery": "Other",
  "70801 - Promo Events|Allie Hafliger Ramp": "Trade Show",
  "70801 - Promo Events|American Express": "Referral",
  "70801 - Promo Events|Tory Burch": "Trade Show",
  "70801 - Promo Events|Fugio cent": "Do Not Tag (COGS/Non-S&M)",
  "70851 - Award Events|DICK'S Sporting Goods": "Partner",
};
