// Key format: "financial_row|entity_name" (pipe separator)
export const PAIR_CLASSIFICATIONS: Record<string, string> = {
  "54051 - EDI Expenses|EDI Health Group": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|Data Media Associates, Inc.": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|DrFirst": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|Change Healthcare (Emdeon)": "Do Not Tag (COGS/Non-S&M)",
  "54051 - EDI Expenses|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "55101 - Software Tools|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "55901 - Fee Guides|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60001 - Wages & Salaries|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60002 - Commissions|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60003 - PTO Wage/Salary Accrual|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60004 - Bonuses|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60125 - US Payroll Taxes|Rippling": "Do Not Tag (COGS/Non-S&M)",
  "60125 - US Payroll Taxes|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|United Health Care": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|Elevate.inc": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|Cigna Healthcare": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|UNUM": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|Restaurant-Misc": "Do Not Tag (COGS/Non-S&M)",
  "60200 - Benefits Program|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|ImpactSearch Partners, LLC": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Direct Recruiters, Inc.": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Zmich Ventures LLC": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Shift Group Holdings, Inc.": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|ISG Partners": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|TechCXO": "Do Not Tag (COGS/Non-S&M)",
  "60300 - Recruitment Costs|Hire With Near LLC": "Do Not Tag (COGS/Non-S&M)",
  "60402 - Employer 4K Expense|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65001 - Utilities - Internet Access|Kenneth Mark Blount Ramp": "Trade Show",
  "65199 - Services - Other/Misc|Vendor-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65199 - Services - Other/Misc|I'm The Chef Too": "Do Not Tag (COGS/Non-S&M)",
  "65199 - Services - Other/Misc|Beam": "Do Not Tag (COGS/Non-S&M)",
  "65199 - Services - Other/Misc|Kenneth Mark Blount Ramp": "Trade Show",
  "65401 - Tools - Software Licenses|StoryPath LLC": "Other",
  "65401 - Tools - Software Licenses|Ethos transforming education": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Retention.com": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Clay Labs Inc": "Sales Development",
  "65401 - Tools - Software Licenses|Semrush": "SEO / Organic",
  "65401 - Tools - Software Licenses|Salesforce": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|monday.com": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Hubspot": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|LinkedIn": "Paid Social",
  "65401 - Tools - Software Licenses|cleverbridge": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|WiseStamp": "Email",
  "65401 - Tools - Software Licenses|Frase": "SEO / Organic",
  "65401 - Tools - Software Licenses|Canva": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Microsoft Advertising": "Paid Search",
  "65401 - Tools - Software Licenses|Eleventh & Gather": "Trade Show",
  "65401 - Tools - Software Licenses|One Click / DrDDS / Recordlinc": "Sales Development",
  "65401 - Tools - Software Licenses|OpenAI": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|HeyReach": "Paid Social",
  "65401 - Tools - Software Licenses|GetEmails": "Other",
  "65401 - Tools - Software Licenses|SPYFU": "SEO / Organic",
  "65401 - Tools - Software Licenses|Spotify Ad Studio": "Paid Search",
  "65401 - Tools - Software Licenses|Gong.io Inc": "Sales Development",
  "65401 - Tools - Software Licenses|Instantly.Ai": "Email",
  "65401 - Tools - Software Licenses|OpportunityMagic": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Netronix Integration": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Aventri": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Kenneth Mark Blount Ramp": "Trade Show",
  "65401 - Tools - Software Licenses|XAPPEX": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Vendor-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Sean Gove Ramp": "Partner",
  "65401 - Tools - Software Licenses|Photoroom": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|QRTiger": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|ManyChat": "Paid Social",
  "65401 - Tools - Software Licenses|Inbox Navigator": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Bitly": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Microsoft": "Paid Search",
  "65401 - Tools - Software Licenses|Interact": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|ElevenLabs": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Serper": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|QR Code Generator": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Zapier": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Squirrels": "Do Not Tag (COGS/Non-S&M)",
  "65401 - Tools - Software Licenses|Moz": "SEO / Organic",
  "65401 - Tools - Software Licenses|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Amazon.com - US": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Vendor-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|BestBuy - US": "Trade Show",
  "65501 - Supplies - General Office|Sean Gove Ramp": "Partner",
  "65501 - Supplies - General Office|Trevor Macon": "Trade Show",
  "65501 - Supplies - General Office|Midwest Dental": "Partner",
  "65501 - Supplies - General Office|Target": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Allie Hafliger Ramp": "Trade Show",
  "65501 - Supplies - General Office|Walgreens": "Trade Show",
  "65501 - Supplies - General Office|The UPS Store": "Trade Show",
  "65501 - Supplies - General Office|Apple": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Harry & David": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Staples - US": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Victoria Lane Ramp": "Trade Show",
  "65501 - Supplies - General Office|Halle Eicher Ramp": "Trade Show",
  "65501 - Supplies - General Office|Monica Cody Clark Ramp": "Trade Show",
  "65501 - Supplies - General Office|Kenneth Mark Blount Ramp": "Trade Show",
  "65501 - Supplies - General Office|Shahrzad Nadizadeh Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Sara Ataollahi Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Prime Video": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Dollar General": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|Shoppers Drug Mart": "Do Not Tag (COGS/Non-S&M)",
  "65501 - Supplies - General Office|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|Fedex": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|USPS": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|MP PACK-N-MAIL": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|Harry & David": "Do Not Tag (COGS/Non-S&M)",
  "65502 - Supplies - Postage|Kenneth Mark Blount Ramp": "Trade Show",
  "65502 - Supplies - Postage|Sarah Lamb Ramp": "Trade Show",
  "65502 - Supplies - Postage|Carlson Chiles Ramp": "Trade Show",
  "65601 - Travel and Lodging|Hotel-Misc (US)": "Trade Show",
  "65601 - Travel and Lodging|Hilton": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Delta Air Lines": "Trade Show",
  "65601 - Travel and Lodging|Gregory Wu DMD": "Trade Show",
  "65601 - Travel and Lodging|American Express": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Kenneth Mark Blount Ramp": "Trade Show",
  "65601 - Travel and Lodging|The Fractional Match LLC (Cassie Tallon)": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Gary Long Ramp": "Trade Show",
  "65601 - Travel and Lodging|The Ritz-Carlton Aruba": "Do Not Tag (COGS/Non-S&M)",
  "65601 - Travel and Lodging|Allie Hafliger Ramp": "Trade Show",
  "65601 - Travel and Lodging|Sean Gove Ramp": "Trade Show",
  "65601 - Travel and Lodging|Jake Weber Ramp": "Trade Show",
  "65601 - Travel and Lodging|United Airlines": "Trade Show",
  "65601 - Travel and Lodging|Jana Macon Ramp": "Trade Show",
  "65601 - Travel and Lodging|Shahrzad Nadizadeh Ramp": "Trade Show",
  "65601 - Travel and Lodging|American Airlines": "Trade Show",
  "65601 - Travel and Lodging|Southwest Airlines": "Trade Show",
  "65601 - Travel and Lodging|Guestrs Hotel": "Trade Show",
  "65601 - Travel and Lodging|Hanna Brittain Ramp": "Trade Show",
  "65601 - Travel and Lodging|Scott Poitevent Ramp": "Trade Show",
  "65601 - Travel and Lodging|Ashleigh Culpepper Ramp": "Trade Show",
  "65601 - Travel and Lodging|Julia Duncan Ramp": "Trade Show",
  "65601 - Travel and Lodging|Trevor Macon": "Trade Show",
  "65601 - Travel and Lodging|Trade Show Planners Ll": "Trade Show",
  "65601 - Travel and Lodging|Sarah Lamb Ramp": "Trade Show",
  "65601 - Travel and Lodging|Andrew Ward Ramp": "Trade Show",
  "65601 - Travel and Lodging|Suzanne Henderson Ramp": "Trade Show",
  "65601 - Travel and Lodging|Carlson Chiles Ramp": "Trade Show",
  "65601 - Travel and Lodging|Travis Grawey Ramp": "Trade Show",
  "65601 - Travel and Lodging|Halle Eicher Ramp": "Trade Show",
  "65601 - Travel and Lodging|Shannon Murry Ramp": "Trade Show",
  "65602 - Meals & Entertainment|Delta Air Lines": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Restaurant-Misc": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Destination Puerto Rico": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Hotel-Misc (US)": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Agency 44 LLC": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Lapdog": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Andrew Ward Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Gary Long Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Jake Weber Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|KAESER BLAIR INCORPORATED": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Gift & Souvenirs": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|CrystalPlus.com": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|American Express": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Gift Card Granny": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Instacart": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Immersive Group Gaming Li": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Chateau Elan Winery & Resort": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Space Needle": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Successories": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Amazon.com - US": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|PayPal": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Publix": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|Name Badge Productions": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|FunKids Sports Association": "Do Not Tag (COGS/Non-S&M)",
  "65602 - Meals & Entertainment|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
  "65901 - Fees - Bank Charges|Chateau Elan Winery & Resort": "Do Not Tag (COGS/Non-S&M)",
  "65901 - Fees - Bank Charges|Gary Long Ramp": "Do Not Tag (COGS/Non-S&M)",
  "65901 - Fees - Bank Charges|25470 Care Credit": "Do Not Tag (COGS/Non-S&M)",
  "69301 - Legal|Freeman Mathis & Gary, LLP": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|KAK Project Management": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Kenneth Mark Blount Ramp": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Bosslady Marketing": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Trevor Macon": "Trade Show",
  "69601 - Consulting Fees Paid|DEBORAH E. BUSH": "SEO / Organic",
  "69601 - Consulting Fees Paid|Gregory Wu DMD": "Trade Show",
  "69601 - Consulting Fees Paid|Hyperscayle LLC": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Edward Cole Henson": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Julia Fuhrman": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Amy Kitti": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Hypha HubSpot Development": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|The Fractional Match LLC (Cassie Tallon)": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|GAVIN MCDONNELL": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Strategic Conferences & Events": "Trade Show",
  "69601 - Consulting Fees Paid|Ben Tanksley": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|RevTech Partners": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Jama Bryan": "Do Not Tag (COGS/Non-S&M)",
  "69601 - Consulting Fees Paid|Chloe Macon": "Paid Social",
  "69601 - Consulting Fees Paid|Magnifident, Inc.": "Referral",
  "69601 - Consulting Fees Paid|ETHAN MCDONNELL": "Do Not Tag (COGS/Non-S&M)",
  "70001 - Direct Mailing Costs|ULINE": "Partner",
  "70001 - Direct Mailing Costs|Sticker Mule": "Trade Show",
  "70001 - Direct Mailing Costs|USPS": "Partner",
  "70501 - Advertising - Print|Smartpress": "Trade Show",
  "70501 - Advertising - Print|Fugio cent": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Google Ads": "Paid Search",
  "70551 - Advertising - Electronic|Facebook": "Paid Social",
  "70551 - Advertising - Electronic|Ascenditt": "Paid Search",
  "70551 - Advertising - Electronic|Capterra": "Review Sites",
  "70551 - Advertising - Electronic|Vibe": "Paid Search",
  "70551 - Advertising - Electronic|Belmont Publications Inc": "Paid Search",
  "70551 - Advertising - Electronic|Dentistry In General": "Partner",
  "70551 - Advertising - Electronic|Breakaway Practice LLC": "Trade Show",
  "70551 - Advertising - Electronic|BURGOS MEDIA LLC": "Paid Social",
  "70551 - Advertising - Electronic|Salem Media Group": "Paid Search",
  "70551 - Advertising - Electronic|Reddit": "Paid Social",
  "70551 - Advertising - Electronic|CrystalPlus.com": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Crystal Central": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Endeavor Business Media": "SEO / Organic",
  "70551 - Advertising - Electronic|Frase": "SEO / Organic",
  "70551 - Advertising - Electronic|Restaurant-Misc": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|American Express": "Referral",
  "70551 - Advertising - Electronic|Semrush": "SEO / Organic",
  "70551 - Advertising - Electronic|ATW Communications (Ricardo Vega)": "Partner",
  "70551 - Advertising - Electronic|Crown Council": "Partner",
  "70551 - Advertising - Electronic|Taboola": "Paid Search",
  "70551 - Advertising - Electronic|Inbox Navigator": "Do Not Tag (COGS/Non-S&M)",
  "70551 - Advertising - Electronic|Parking": "Trade Show",
  "70599 - Advertising - Other|The Fractional Match LLC (Cassie Tallon)": "Partner",
  "70599 - Advertising - Other|Chloe Macon": "Paid Social",
  "70599 - Advertising - Other|Stock Supply LLC": "Trade Show",
  "70599 - Advertising - Other|Software Advice": "Review Sites",
  "70599 - Advertising - Other|American Express": "Referral",
  "70599 - Advertising - Other|Cision US Inc.": "SEO / Organic",
  "70599 - Advertising - Other|Dentaltown.com LLC": "Paid Search",
  "70599 - Advertising - Other|Minuteman Press Suwanee A Division of Diversified Printing Solutions Inc.": "Trade Show",
  "70599 - Advertising - Other|Adam C. Garrett": "Do Not Tag (COGS/Non-S&M)",
  "70599 - Advertising - Other|Crown Council": "Partner",
  "70599 - Advertising - Other|Zar Dental Consulting": "Referral",
  "70599 - Advertising - Other|Dr. Scott Leune": "Trade Show",
  "70599 - Advertising - Other|Google Ads": "Paid Search",
  "70599 - Advertising - Other|Whova": "Do Not Tag (COGS/Non-S&M)",
  "70599 - Advertising - Other|Comfort Dental Group, Inc": "Partner",
  "70599 - Advertising - Other|Midtown Technology Group (Michael DeWitt)": "Partner",
  "70599 - Advertising - Other|Solution Start Corp. (Jimmy Georgiou) Demetrios Andritsogiannis": "Partner",
  "70599 - Advertising - Other|1201AM CREATIVE, LLC": "SEO / Organic",
  "70599 - Advertising - Other|Masserano Real Estate Consulting": "Partner",
  "70599 - Advertising - Other|Inland IT": "Partner",
  "70599 - Advertising - Other|Infinity Data Comm Inc.": "Partner",
  "70599 - Advertising - Other|Lightning IT Services, Inc.": "Partner",
  "70599 - Advertising - Other|AccommoDental Media": "Partner",
  "70599 - Advertising - Other|Delmain Analytics LLC": "Partner",
  "70599 - Advertising - Other|ATW Communications (Ricardo Vega)": "Partner",
  "70599 - Advertising - Other|Xcalibur Design": "Partner",
  "70599 - Advertising - Other|Carla Cohn": "Referral",
  "70599 - Advertising - Other|Florida Dental": "Trade Show",
  "70599 - Advertising - Other|Colleen Huff": "Referral",
  "70599 - Advertising - Other|Spotify Ad Studio": "Paid Social",
  "70599 - Advertising - Other|(No vendor — journal/payroll/accrual)": "Other",
  "70601 - Trade Show - Registrations|Dr. Scott Leune": "Trade Show",
  "70601 - Trade Show - Registrations|Gregory Wu DMD": "Trade Show",
  "70601 - Trade Show - Registrations|Clear Coaching Ltd.": "Trade Show",
  "70601 - Trade Show - Registrations|Crown Council": "Trade Show",
  "70601 - Trade Show - Registrations|Dental Boards Ace": "Trade Show",
  "70601 - Trade Show - Registrations|UMKC Dental Alumni": "Trade Show",
  "70601 - Trade Show - Registrations|Freeman": "Trade Show",
  "70601 - Trade Show - Registrations|AAP": "Trade Show",
  "70601 - Trade Show - Registrations|Shepard Exposition Services Inc": "Trade Show",
  "70601 - Trade Show - Registrations|American Academy of Dental Practice Administration": "Trade Show",
  "70601 - Trade Show - Registrations|Carla Cohn": "Trade Show",
  "70601 - Trade Show - Registrations|Greater Atlanta Dental Foundation": "Trade Show",
  "70601 - Trade Show - Registrations|Oregon Convention Center": "Trade Show",
  "70601 - Trade Show - Registrations|Eventbrite": "Trade Show",
  "70601 - Trade Show - Registrations|Connecticut State Dental Association": "Trade Show",
  "70601 - Trade Show - Registrations|Connecticut Society Of": "Trade Show",
  "70601 - Trade Show - Registrations|EFFECTIVE DENTISTRY": "Trade Show",
  "70601 - Trade Show - Registrations|Dallas County Dental Society": "Trade Show",
  "70601 - Trade Show - Registrations|Atlanta Dental Supply": "Trade Show",
  "70601 - Trade Show - Registrations|COLORADO CONVETION CENTER": "Trade Show",
  "70601 - Trade Show - Registrations|Ontario Dental Association": "Trade Show",
  "70601 - Trade Show - Registrations|Convention Data Services": "Trade Show",
  "70601 - Trade Show - Registrations|Restaurant-Misc": "Trade Show",
  "70601 - Trade Show - Registrations|MidwestDental": "Trade Show",
  "70601 - Trade Show - Registrations|Smile Source": "Trade Show",
  "70601 - Trade Show - Registrations|Gift Card": "Trade Show",
  "70601 - Trade Show - Registrations|Amazon.com - US": "Trade Show",
  "70601 - Trade Show - Registrations|Hotel-Misc (US)": "Trade Show",
  "70601 - Trade Show - Registrations|National Denturist Association": "Trade Show",
  "70601 - Trade Show - Registrations|Fedex": "Trade Show",
  "70601 - Trade Show - Registrations|Sam's Club": "Trade Show",
  "70601 - Trade Show - Registrations|Robin Bowling Ramp": "Trade Show",
  "70601 - Trade Show - Registrations|Lidl": "Trade Show",
  "70601 - Trade Show - Registrations|(No vendor — journal/payroll/accrual)": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|KAESER BLAIR INCORPORATED": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Exhibits South": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Halo Branded Solutions": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Freeman": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Expoprep": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Dr. Scott Leune": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Smile Source": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Metro Denver Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Hinman Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Aramark Services, Inc": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Washington State Denta": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Trade Show Planners Ll": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Seattle Convention Center": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Sodexo Live!": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|JW Marriott Camelback Inn": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|McCormick Place": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Jack Nadel International": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Ags Expo": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Restaurant-Misc": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|GES": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Cision US Inc.": "SEO / Organic",
  "70602 - Trade Show - Materials and Rentals|PSAV": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Fern Expo": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Gregory Wu DMD": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Florida Dental": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Virtual Dontics": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Allie Hafliger Ramp": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Tory Burch": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|1201AM CREATIVE, LLC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|The Fractional Match LLC (Cassie Tallon)": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Aadom": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|EDI Health Group": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Dental Medical Billing": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Prg": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Don Ross Nabb Production Companies": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Massachusetts Convention Center Authority": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Amazon.com - US": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Maritz Global Events": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|ASN, INC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Ccld": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Demers Exposition Services": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|MARITZ": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Advanced Tradeshow Technology": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Opportunityretreiv": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Chicago Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Colleen Huff": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|projection.com": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Spectrum Audio Visual": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Eleventh & Gather": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|OPTEL TECHNOLOGY LLC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Custom Registration": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Dental Boards Ace": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Table Covers": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|A-1 Rentals": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Mid-Continent Dental Congress": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Greater St. Louis Dental Society": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Jp Display": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Production company": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|TRENDY REP GROUP INC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|ARPA-E": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|TRADESHOW MULTIMEDIA INC": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Sticker Mule": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|OfficeSignCompany": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Sean Gove Ramp": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Displays2go": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Hollister": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Edlen Electrical Exhibition Services": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Jonlee Anderson Ramp": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Wscc Pfd": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Joy Displays": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|AAP": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|B&H Photo": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|PlatePass": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Connecticut State Dental Association": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|Spotify Ad Studio": "Trade Show",
  "70602 - Trade Show - Materials and Rentals|(No vendor — journal/payroll/accrual)": "Trade Show",
  "70801 - Promo Events|Amazon.com - US": "Other",
  "70801 - Promo Events|Smiles For Recovery": "Other",
  "70801 - Promo Events|Allie Hafliger Ramp": "Trade Show",
  "70801 - Promo Events|American Express": "Referral",
  "70801 - Promo Events|Tory Burch": "Trade Show",
  "70801 - Promo Events|Fugio cent": "Do Not Tag (COGS/Non-S&M)",
  "70851 - Award Events|DICK'S Sporting Goods": "Partner",
  "48501 - Partnership Commissions|-Unassigned-": "Partner",
  "48501 - Partnership Commissions|24601 Jive": "Partner",
  "48501 - Partnership Commissions|26533 Blue": "Partner",
  "48501 - Partnership Commissions|30253 Mes": "Partner",
  "48501 - Partnership Commissions|31146 Bird": "Partner",
  "48501 - Partnership Commissions|36005 Glob": "Partner",
  "48501 - Partnership Commissions|37755 Man": "Partner",
  "48501 - Partnership Commissions|38306 Zoc": "Partner",
  "48501 - Partnership Commissions|39565 EDI": "Partner",
  "48501 - Partnership Commissions|42684 AirP": "Partner",
  "48501 - Partnership Commissions|9959 Natio": "Partner",
  "94500 - Severance Payments|(No vendor — journal/payroll/accrual)": "Do Not Tag (COGS/Non-S&M)",
};
